---
title: 'Module 1: Connect to Data and Explore '
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    number_sections: true
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(RSocrata) # connects to Socrata Open Data sources
library(tigris) # connects to census data, shapefiles and more
library(tidyverse) # data manipulation funpack 
library(leaflet) # builds great maps 
```

# Project Setup, Connecting to APIs, Exploration

Mission statement: Find a way to compare schools in New York state by common elements, such as demographic makeup, census data, academic performance, and any other metrics that might be relevant. 

## Project setup and using renv 

It is essential to start all work in R as a Project. This keeps all scripts and data sources in a self contained folder which is helpful for maintaining referential integrity and easy syncing to a remote github repo. Rstudio makes it very easy to work with Projects, and users should take notice. 

`renv` is a library that creates a virtual environment for your R project. In contrast to some of my experiences in python, this virtual environment is fairly painless. After installing and running renv, the user gets a lockfile that keeps track of all libraries and versions. This is a big deal when it comes to reproducing results and getting the script to work on someone else's computer. 

## Connecting to a API 

For this project, we want to connect to Socrata and download open source data. Socrata provides multiple ways to do this. It is possible to obtain data via: 

1. Export as csv and load into R
2. Export as json or other formats and load into R 
3. Connect to Socrata Open Data API (SODA API). This allows a user to connect with an API endpoint and filter, query, and aggregate data by manipulating a URL string. 
4. Connect to OData v4. A user can connect directly to Excel or Tableau with this method. 

We will use method 3, and connect via the SODA API endpoint. If we import data into our R Project from a downloaded file, we risk using outdated data if it is later updated. Using an API connection ensures that we are always using the most updated data. 

## Creating dataframes and checking data integrity amongst data sources 



## Light EDA using glimpse, summary and gt 

## Hands-on Activity/Exercise


